# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'CurrencyChecker’ do

pod 'AFNetworking', '~> 3.0'
pod 'JSONModel'

end

target 'CurrencyCheckerTests’ do

end

target 'CurrencyCheckerUITests’ do

end
